/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.map.crudproduto.UI;

import br.com.map.crudproduto.model.Produto;
import br.com.map.crudproduto.util.MensagensUtil;

/**
 *
 * @author natan
 */
public class ProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoView
     * @param p
     */
    public ProdutoView(Produto p) {
                              
        initComponents();
        
        CodigoLabel.setText (MensagensUtil.getMensagem(MensagensUtil.MENSAGEM_LABEL_CODIGO));
        NomeLabel.setText(MensagensUtil.getMensagem(MensagensUtil.MENSAGEM_LABEL_NOME));
        PrecoLabel.setText(MensagensUtil.getMensagem(MensagensUtil.MENSAGEM_LABEL_PRECO));
        FabricanteLabel.setText(MensagensUtil.getMensagem(MensagensUtil.MENSAGEM_LABEL_FABRICANTE));
        CorLabel.setText(MensagensUtil.getMensagem(MensagensUtil.MENSAGEM_LABEL_COR));
        SistemaLabel.setText(MensagensUtil.getMensagem(MensagensUtil.MENSAGEM_LABEL_SISTEMA));
        DetalhesLabel.setText(MensagensUtil.getMensagem(MensagensUtil.MENSAGEM_LABEL_DETALHES));
        
        CodigoText.setText (""+p.getCodigo());
        NomeText.setText(p.getNome());
        PrecoText.setText(""+p.getPreco());
        FabricanteText.setText(p.getEspecificacao().getFabricante());
        CorText.setText(p.getEspecificacao().getCor());
        SistemaText.setText(p.getEspecificacao().getSistema());
        DetalhesPainel.setText(p.getEspecificacao().getDetalhes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NomeLabel = new javax.swing.JLabel();
        PrecoLabel = new javax.swing.JLabel();
        CodigoLabel = new javax.swing.JLabel();
        FabricanteLabel = new javax.swing.JLabel();
        CorLabel = new javax.swing.JLabel();
        SistemaLabel = new javax.swing.JLabel();
        DetalhesLabel = new javax.swing.JLabel();
        InformacoesText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetalhesPainel = new javax.swing.JTextPane();
        FabricanteText = new javax.swing.JTextField();
        PrecoText = new javax.swing.JTextField();
        NomeText = new javax.swing.JTextField();
        CodigoText = new javax.swing.JTextField();
        CorText = new javax.swing.JTextField();
        SistemaText = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(623, 470));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(616, 460));

        NomeLabel.setText("Nome:");

        PrecoLabel.setText("Preço:");

        CodigoLabel.setText("Codigo:");

        FabricanteLabel.setText("Fabricante:");

        CorLabel.setText("Cor:");

        SistemaLabel.setText("Sistema:");

        DetalhesLabel.setText("Detalhes:");

        InformacoesText.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        InformacoesText.setText("Informações do Produto-");

        DetalhesPainel.setEditable(false);
        jScrollPane1.setViewportView(DetalhesPainel);

        FabricanteText.setEditable(false);

        PrecoText.setEditable(false);

        NomeText.setEditable(false);

        CodigoText.setEditable(false);

        CorText.setEditable(false);

        SistemaText.setEditable(false);

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(InformacoesText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OKButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FabricanteLabel)
                                    .addComponent(PrecoLabel)
                                    .addComponent(NomeLabel)
                                    .addComponent(CodigoLabel)
                                    .addComponent(CorLabel)
                                    .addComponent(SistemaLabel)
                                    .addComponent(DetalhesLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SistemaText, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                                        .addComponent(FabricanteText)
                                        .addComponent(PrecoText)
                                        .addComponent(NomeText)
                                        .addComponent(CodigoText)
                                        .addComponent(CorText))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(InformacoesText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoLabel)
                    .addComponent(CodigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(NomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecoLabel)
                    .addComponent(PrecoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FabricanteLabel)
                    .addComponent(FabricanteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorLabel)
                    .addComponent(CorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SistemaLabel)
                    .addComponent(SistemaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DetalhesLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OKButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_OKButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodigoLabel;
    private javax.swing.JTextField CodigoText;
    private javax.swing.JLabel CorLabel;
    private javax.swing.JTextField CorText;
    private javax.swing.JLabel DetalhesLabel;
    private javax.swing.JTextPane DetalhesPainel;
    private javax.swing.JLabel FabricanteLabel;
    private javax.swing.JTextField FabricanteText;
    private javax.swing.JLabel InformacoesText;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField NomeText;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel PrecoLabel;
    private javax.swing.JTextField PrecoText;
    private javax.swing.JLabel SistemaLabel;
    private javax.swing.JTextField SistemaText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
